/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let sum = 0;
let maxValue = 4000000
for (let num1 = 0, num2=1; num2<4000000;) {
    let actualNum = num1+num2;
    num1 = num2;
    num2 = actualNum; 

    sum += actualNum % 2 == 0 ? actualNum : 0; 
}

console.log(sum)